name: Tests
on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        make
        make examples

    - name: Unit tests
      run: |
        make libcheck
        make test

    - name: Upload the coverage
      if: github.ref == 'refs/heads/master'
      uses: codecov/codecov-action@v1

  OSX:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        make
        make examples
